org: dotenv
app: aws-lambda
service: aws-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DOTENV_KEY: ${param:DOTENV_KEY}

functions:
  function1:
    handler: index.handler

package:
  patterns:
    - '!.env*'
    - '.env.vault'
