# fly.toml app configuration file generated for holy-sun-8759 on 2023-07-29T12:44:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "holy-sun-8759"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
